// connection
export const OPEN_CONNECTION = 'OPEN_CONNECTION'
export const CLOSE_CONNECTION = 'CLOSE_CONNECTION'
export const CONNECTION_OPENED = 'CONNECTION_OPENED'
export const CONNECTION_CLOSED = 'CONNECTION_CLOSED'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'

// game
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const CHANGE_GAME_MODE = 'CHANGE_GAME_MODE'
export const SET_CURSOR = 'SET_CURSOR'
export const SET_RETICULE = 'SET_RETICULE'
export const SET_TARGET = 'SET_TARGET'

// keyboard
export const FOCUS_KEYBOARD = 'FOCUS_KEYBOARD'
export const BLUR_KEYBOARD = 'BLUR_KEYBOARD'
