// connection
export const OPEN_CONNECTION = 'OPEN_CONNECTION'
export const CLOSE_CONNECTION = 'CLOSE_CONNECTION'
export const CONNECTION_OPENED = 'CONNECTION_OPENED'
export const CONNECTION_CLOSED = 'CONNECTION_CLOSED'
export const RECEIVE_GAME_START = 'RECEIVE_GAME_START'
export const RECEIVE_GAME_UPDATE = 'RECEIVE_GAME_UPDATE'
export const RECEIVE_GAME_OVER = 'RECEIVE_GAME_OVER'
export const RECEIVE_AREA_CHANGE = 'RECEIVE_AREA_CHANGE'
export const RECEIVE_PLAYER_INVENTORY = 'RECEIVE_PLAYER_INVENTORY'

// game
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const CHANGE_GAME_MODE = 'CHANGE_GAME_MODE'
export const SET_CURSOR = 'SET_CURSOR'
export const SET_RETICULE = 'SET_RETICULE'
export const SET_TARGET = 'SET_TARGET'

// keyboard
export const FOCUS_KEYBOARD = 'FOCUS_KEYBOARD'
export const BLUR_KEYBOARD = 'BLUR_KEYBOARD'
