// connection
export const OPEN_CONNECTION = 'OPEN_CONNECTION'
export const CLOSE_CONNECTION = 'CLOSE_CONNECTION'
export const CONNECTION_OPENED = 'CONNECTION_OPENED'
export const CONNECTION_CLOSED = 'CONNECTION_CLOSED'

export const RECEIVE_GAMES = 'RECEIVE_GAMES'
export const CREATE_GAME = 'CREATE_GAME'
export const RECEIVE_CREATE_GAME_FAILED = 'RECEIVE_CREATE_GAME_FAILED'
export const SET_NEW_GAME_PLAYER = 'SET_NEW_GAME_PLAYER'

export const RECEIVE_GAME_START = 'RECEIVE_GAME_START'
export const RECEIVE_GAME_UPDATE = 'RECEIVE_GAME_UPDATE'
export const RECEIVE_GAME_OVER = 'RECEIVE_GAME_OVER'
export const RECEIVE_AREA_CHANGE = 'RECEIVE_AREA_CHANGE'
export const RECEIVE_PLAYER_INVENTORY = 'RECEIVE_PLAYER_INVENTORY'
export const RECEIVE_PLAYER_SETTINGS = 'RECEIVE_PLAYER_SETTINGS'
export const RECEIVE_SIGNAL_MAP = 'RECEIVE_SIGNAL_MAP'
export const RECEIVE_WORLD_INFO = 'RECEIVE_WORLD_INFO'

// crafting
export const SET_CRAFTING_TAB = 'SET_CRAFTING_TAB'
export const SET_CRAFTING_ROW = 'SET_CRAFTING_ROW'

// debug
export const CHANGE_DEBUG_MODE = 'CHANGE_DEBUG_MODE'
export const RECEIVE_DEBUG_FOV = 'RECEIVE_DEBUG_FOV'
export const RECEIVE_DEBUG_WAYPOINT = 'RECEIVE_DEBUG_WAYPOINT'

// game
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const CHANGE_GAME_MODE = 'CHANGE_GAME_MODE'
export const SET_CURSOR = 'SET_CURSOR'
export const SET_INTERACTION = 'SET_INTERACTION'
export const SET_INTERACTIONS = 'SET_INTERACTIONS'
export const SET_RETICULE = 'SET_RETICULE'
export const SET_TARGET = 'SET_TARGET'
export const STORE_GAME_VIEW_SIZE = 'STORE_GAME_VIEW_SIZE'

// inventory
export const SET_INVENTORY_TAB = 'SET_INVENTORY_TAB'
export const SET_INVENTORY_ROW = 'SET_INVENTORY_ROW'
export const SET_INVENTORY_ACTION = 'SET_INVENTORY_ACTION'

// keyboard
export const FOCUS_KEYBOARD = 'FOCUS_KEYBOARD'
export const BLUR_KEYBOARD = 'BLUR_KEYBOARD'

// look
export const SET_LOOK_DETAILED = 'SET_LOOK_DETAILED'
