export const MAIN = 'MAIN'
export const AIM = 'AIM'
export const INVENTORY = 'INVENTORY'
export const KEY_BINDINGS = 'KEY_BINDINGS'
export const LOOK = 'LOOK'
export const MESSAGE_LOG = 'MESSAGE_LOG'
