export const SELECT_MODEL = 'SELECT_MODEL'
export const SELECT_ITEM = 'SELECT_ITEM'
export const ADD_ITEM = 'ADD_ITEM'
export const SET_ADD_ITEM_ID = 'SET_ADD_ITEM_ID'
export const SET_ITEM_VALUE = 'SET_ITEM_VALUE'
export const SAVE = 'SAVE'
export const SAVED = 'SAVED'
