export const SELECT_MODEL = 'SELECT_MODEL'
export const SELECT_ITEM = 'SELECT_ITEM'
export const ADD_ITEM = 'ADD_ITEM'
export const SET_ADD_ITEM_ID = 'SET_ADD_ITEM_ID'
export const SET_ITEM_VALUE = 'SET_ITEM_VALUE'
export const SAVE = 'SAVE'
export const SAVED = 'SAVED'
export const SHOW_SIDE_FORM = 'SHOW_SIDE_FORM'
export const HIDE_SIDE_FORM = 'HIDE_SIDE_FORM'

export const SET_EDITOR_BRUSH = 'SET_EDITOR_BRUSH'
export const SET_EDITOR_LOCATION = 'SET_EDITOR_LOCATION'
